# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.0.post1.dev1+g0abaf22.d20230110'
__version_tuple__ = version_tuple = (0, 0, 'dev1', 'g0abaf22.d20230110')
